name = "UHDAPI"
uuid = "88b9fb92-0a92-4565-b203-7b4972b7e638"
authors = ["Markus Wirsing <markus.wirsing@gmx.de>"]
version = "0.4.0"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
UHDBindings = "4d90b16f-829e-4b78-80d9-fb9bcf8c06e0"

[compat]
julia = "1.8"
Match = "^1"
